import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Page_links from './links/page'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Second-Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>

    <html lang="en">
    <head>
        <link rel='icon' href='/favicon.jpg'/>
      </head>

      <body>{children}

        {/* Links to jump one page to another */}
        <Page_links/>
        {/* you can find the component i.e the "Page_links" functional component in "page.jsx" link folder  */}
</body>
    </html>
    
    </>
  )
}
